name: fitnessapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.2.3
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Ensure this folder exists and contains images

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf  # Use forward slashes here
        - asset: assets/font/Poppins-Regular.ttf
          weight: 700
